import {
  Wallet,
  PiggyBank,
  Laptop,
  Tag,
  Award,
  ArrowLeftRight,
  RotateCcw,
  TrendingUp,
  Home,
  Zap,
  Wifi,
  ShoppingBasket,
  SprayCan,
  Fuel,
  Car,
  Bus,
  Wrench,
  HeartPulse,
  Dumbbell,
  Sparkles,
  Dog,
  UtensilsCrossed,
  Beer,
  Clapperboard,
  Plane,
  ShoppingBag,
  Gamepad2,
  Tv,
  GraduationCap,
  BookOpen,
  Landmark,
  CreditCard,
  AlertTriangle,
  LineChart,
  ShieldCheck,
} from 'lucide-react';

/**
 * Icon choices offered when creating/editing a category — closed set so new
 * custom categories can still pick something recognizable instead of falling
 * back to the generic tag icon.
 */
export const ICON_MAP = {
  wallet: Wallet,
  piggyBank: PiggyBank,
  laptop: Laptop,
  tag: Tag,
  award: Award,
  arrowLeftRight: ArrowLeftRight,
  rotateCcw: RotateCcw,
  trendingUp: TrendingUp,
  home: Home,
  zap: Zap,
  wifi: Wifi,
  shoppingBasket: ShoppingBasket,
  sprayCan: SprayCan,
  fuel: Fuel,
  car: Car,
  bus: Bus,
  wrench: Wrench,
  heartPulse: HeartPulse,
  dumbbell: Dumbbell,
  sparkles: Sparkles,
  dog: Dog,
  utensilsCrossed: UtensilsCrossed,
  beer: Beer,
  clapperboard: Clapperboard,
  plane: Plane,
  shoppingBag: ShoppingBag,
  gamepad2: Gamepad2,
  tv: Tv,
  graduationCap: GraduationCap,
  bookOpen: BookOpen,
  landmark: Landmark,
  creditCard: CreditCard,
  alertTriangle: AlertTriangle,
  lineChart: LineChart,
  shieldCheck: ShieldCheck,
};

export function getIcon(iconKey) {
  return ICON_MAP[iconKey] ?? Tag;
}
